import Head from 'next/head'
import Image from 'next/image'
import ReactHowler from 'react-howler'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import sound from './music/newstart.mp3'
import useSound from 'use-sound';
import { useEffect,useRef,useState } from 'react'
import * as Icon from 'react-feather';
import Gsap from 'gsap';

export default function Home() {

  const [scrollY, setScrollY] = useState(0)
  const [isModal, setIsModal] = useState(false);
  const [playing, setPlaying] = useState(false);
  const videoRef = useRef(null);
  let openh1 = false

  const handleScroll = () => {
    setScrollY(window.scrollY)
    if (window.scrollY > 340) {
      if (openh1 == false) {
        openh1 = true
      }
    }
  }

  useEffect(()=> {
    window.addEventListener('scroll', handleScroll )
  }, [])

  //タイトル
  let title = "動画編集からシステム開発まで！\n"
  title += "なんでも請負ます！！\n"

  let moji = "";

  // 紹介欄
  let introduce = "上記の悩みや、小規模なシステム開発から大規模なシステム開発\n"
  introduce += "動画編集、画像編集などといったクリエイティブ系も\n"
  introduce += "喜んでお請け致します。\n"
  introduce += "是非一度お問い合わせくださいませ！！"

  const memochou = [
    " Webサイトを作りたいけど、どうしたらいいのかわからない",
    " メルカリ、ヤフオク自動で出品・管理できたらいいな・・・",
    " 問い合わせ用チャットbotが欲しい。",
    " 結婚式の動画編集を頼みたい。",
    " YouTubeで使うコラ画像を作って欲しい。"
  ]

  const mlist = function(){
    var items = [];
    for (var i = 0; i<memochou.length; i++){
      items.push(
          <li>
            {memochou[i]}
          </li>
      )
    }
    return (<ul className={styles.note}>{items}</ul>)
  }

  let caption = "Call from 'Ryukyu Island'.";

  const dropout = function(){
    Gsap.to('#fadeOut',{
      opacity: 0,
      duration: 1,
      display: "none",
    })
    setPlaying(true);
    videoRef.current.play();
    Gsap.to('#caption',{
      delay: 4,
      display: "block",
      opacity: 1,
      y: -120
    })
    Gsap.to('#caption',{
      delay: 1,
      opacity: 0,
      display: "none",
      y: -30
    })
    caption = "Call from 'Ryukyu Island'.";

    
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReactHowler
          src={["./greeenasassindollar.mp3"]}
          playing={playing}
          volume={0.4}
          loop={true}
      />
      <main className={styles.main}>
        <header className={styles.headings}>
          <div className={styles.videoarea}>
            <video
            src="greeenasassindollar.mp4"
            ref={videoRef}
            loop
            muted
            className={styles.video}
            id="video"
            />
          </div>
          <div className={styles.buttonszokusei} id="fadeOut" onClick={dropout}>
            Click to Display!!
          </div>
          <div className={styles.caption} id="caption">
            {caption}
          </div>
        </header>
        <div className={styles.contents}>
          <Image src='/logo.png' width={700} height={100} className='ml-3 mb-10 mt-10 inline' />
          <h2 className={styles['he-2']}>{title}</h2>
          { mlist() }
          <p className={styles['fesize']}>{introduce}</p>
          <div className={styles.howbtn}>
              <a href="/contact">
                <div className={styles.exampleClass}>お問い合わせ<Icon.Mail className={styles.mailicon}/></div>
              </a>
          </div>
        </div>
      </main>
    </>
  )
}
